export const dummyProducts = [
    {
      id: 1,
      name: "Inhale - Exhale - Grey",
      price: 29.95,
      photo: "/img/1.jpg",
      material: "100% cotton",
      brand: "Gildan",
    },
    {
      id: 2,
      name: "Pizza Pocket - Black",
      price: 15.95,
      photo: "/img/2.jpg",
      material: "90% cotton, 10% polyester",
      brand: "Gildan",
    },
    {
      id: 3,
      name: "I am the storm - Navy blue",
      price: 19.99,
      photo: "/img/3.jpg",
      material: "100% cotton",
      brand: "Gildan",
    },
    {
      id: 4,
      name: "Regal - Beagle",
      price: 25.90,
      photo: "/img/4.jpg",
      material: "90% cotton, 10% polyester",
      brand: "Gildan",
    },
    {
      id: 5,
      name: "4th of July Cat - Americat",
      price: 9.85,
      photo: "/img/5.jpg",
      material: "90% cotton, 10% polyester",
      brand: "Gildan",
    },
    {
      id: 6,
      name: "Double AA - Meeting",
      price: 24.95,
      photo: "/img/6.jpg",
      material: "100% cotton",
      brand: "Gildan",
    },
    {
      id: 7,
      name: "Ice cream yoga pants",
      price: 79.95,
      photo: "/img/7.jpg",
      material: "100% lycra",
      brand: "Gildan",
    },
    {
      id: 8,
      name: "Galaxy yoga pants",
      price: 134.99,
      photo: "/img/8.jpg",
      material: "100% Spandex",
      brand: "Gildan",
    },
    {
      id: 9,
      name: "Disco Inferno - Yoga pants",
      price: 99.99,
      photo: "/img/9.jpg",
      material: "100% Spandex",
      brand: "Gildan",
    },
    {
      id: 10,
      name: "Triangle Yoga pants",
      price: "79.99",
      photo: "/img/10.jpg",
      material: "100% Spandex",
      brand: "Gildan",
    },
    {
        id: 11,
        name: "Triangle Yoga pants - Black",
        price: "89.95",
        photo: "/img/10.jpg",
        material: "100% lycra",
        brand: "Gildan",
      },
  ];
  